// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCkZg_Pk4Iw1UxkpqqiyoroLLSVKoD3Fj8',
    appId: '1:441211470185:web:7d3ee2eca6ee077c5f3df8',
    messagingSenderId: '441211470185',
    projectId: 'clipit-2e405',
    authDomain: 'clipit-2e405.firebaseapp.com',
    storageBucket: 'clipit-2e405.firebasestorage.app',
    measurementId: 'G-G38X95W7LK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDBy0f04BrEAjOqWBTSa8oNExTpxJmHxsg',
    appId: '1:441211470185:android:82511bb71668135d5f3df8',
    messagingSenderId: '441211470185',
    projectId: 'clipit-2e405',
    storageBucket: 'clipit-2e405.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB2WjU93MEIRhzY8XeXsAWODt0FTEaUSt4',
    appId: '1:441211470185:ios:9f1df32800fc6b7e5f3df8',
    messagingSenderId: '441211470185',
    projectId: 'clipit-2e405',
    storageBucket: 'clipit-2e405.firebasestorage.app',
    iosBundleId: 'com.example.clipitFront',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB2WjU93MEIRhzY8XeXsAWODt0FTEaUSt4',
    appId: '1:441211470185:ios:9f1df32800fc6b7e5f3df8',
    messagingSenderId: '441211470185',
    projectId: 'clipit-2e405',
    storageBucket: 'clipit-2e405.firebasestorage.app',
    iosBundleId: 'com.example.clipitFront',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCkZg_Pk4Iw1UxkpqqiyoroLLSVKoD3Fj8',
    appId: '1:441211470185:web:01c59684021e0df95f3df8',
    messagingSenderId: '441211470185',
    projectId: 'clipit-2e405',
    authDomain: 'clipit-2e405.firebaseapp.com',
    storageBucket: 'clipit-2e405.firebasestorage.app',
    measurementId: 'G-NNFT5WZ2NP',
  );
}
